### PR TITLE
Update rust-toolchain to nightly-2019-05-22

### PR DESCRIPTION
**Pull request by elichai**
`rust-toolchain` file doesn't match baidu's toolchain https://github.com/baidu/rust-sgx-sdk/commit/e0fa56e7deca38fdba3797b345a0a46b696edd8b

This should also fix the annoying `no_mangle` warnings https://github.com/rust-lang/rust/issues/60050

### CODE REVIEW

**Review by AvishaiW — APPROVED** [review]
Thanks! surprised I didn't get an alert on this change

**Comment by moriaab** [comment]
Thank you @elichai!

**Comment by lacabra** [comment]
The CI build is failing with the following error:
```
bindgen Enclave_t.h --default-enum-style=rust --rust-target=nightly --no-recursive-whitelist --use-array-pointers-in-arguments --whitelist-function ocall_.* --raw-line "#![allow(dead_code)] use enigma_types::*; use sgx_types::*;" -- -I/opt/sgxsdk/include -I/root/sgx/edl > src/auto_ffi.rs
--
126 | error: 'rustfmt' is not installed for the toolchain 'nightly-2019-05-22-x86_64-unknown-linux-gnu'
127 | To install, run `rustup component add rustfmt --toolchain nightly-2019-05-22-x86_64-unknown-linux-gnu`
128 | Failed to run rustfmt: Internal rustfmt error (non-fatal, continuing)
129 | rustfmt src/auto_ffi.rs
130 | error: 'rustfmt' is not installed for the toolchain 'nightly-2019-05-22-x86_64-unknown-linux-gnu'
131 | To install, run `rustup component add rustfmt --toolchain nightly-2019-05-22-x86_64-unknown-linux-gnu`
132 | Makefile:30: recipe for target 'bindgen' failed
```

I have observed this error already, and reported it on #183, and provided a fix in enigmampc/discovery-docker-network#26, but it looks like this requires a fix in `enigma-core/Dockerfile/dockerfile` and push an updated docker image for `enigmampc/enigma-core`

Cc: @AvishaiW, @moriaab

**Comment by AvishaiW** [comment]
@lacabra there are some toolchain updates with breaking changes. in a situation that you upgrade manually, make sure you run the rustup add command as well: 
`rustup target add wasm32-unknown-unknown && rustup component add rustfmt`, i've done it and it seems to run just fine.

**Comment by AvishaiW** [comment]
@elichai since you aren't a member, the CI won't trigger. so, unfortunately, I need to close and reopen this PR with my user. Thank you very much for the notification and contribution!

**Pull request closed without merging**
