### PR TITLE
FIX: Fixed an issue with using Hash256 in the epoch state and added a…

### PR DESCRIPTION
**Pull request by fredfortier**
It seems like Serde does not automatically serialize Struct HashMap keys so I implemented a custom serializer. I also added a unit test to catch this sort of issue in the future. This was caught be `Enigma.spec.js` but unit tests did not have sufficient coverage.

This should resolve issue #110.

### CODE REVIEW

**Comment by lacabra** [comment]
I confirm that this PR does indeed resolve the issue in the docker network. Thank you

**Comment by elichai** [comment]
the problem is that you use serde-json to serialize the struct and JSON's keys are required to be strings.
I think the right solution is to just not use serde-json and instead use a different serializer (i.e. MessagePack)

it will work:
```
use rmp_serde::{Serializer, Deserializer};
use serde::{Serialize, Deserialize};
use std::collections::HashMap;


#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Hash256(pub [u8; 32]);

#[derive(Serialize, Deserialize, PartialEq, Debug)]
struct Test {
    pub map: HashMap<Hash256, u32>,
}


fn main() {
    let mut a = Test{map: HashMap::new()};
    a.map.insert(Hash256([17u8; 32]), 58);
    let mut buf = Vec::new();
    a.serialize(&mut Serializer::new(&mut buf)).unwrap();
    let mut des = Deserializer::new(&buf[..]);
     let b: Test = Deserialize::deserialize(&mut des).unwrap();
     assert_eq!(a,b);
}
```

**Comment by fredfortier** [comment]
I don't see how using MessagePack over JSON is the "right solution" but I'll make the suggested change.

**Comment by elichai** [comment]
Because what this is doing is lying that hash256 is actually hex. And converting it back and forth.
When the obvious solution is that the serialization you used wasn't suitable.

Correct me if I'm wrong but no human should understand/read this, Right?

**Comment by fredfortier** [comment]
All other things being equal, I would prefer serializing the epoch state in a human readable format if only to help investigate a failure scenario. That said, it is a marginal benefit and I'm not opposed to your suggestion. I just do not believe that phrasing your suggestion in the absolute form is appropriate.

**Comment by fredfortier** [comment]
Implemented MessagePack encoding.

**Review by elichai — APPROVED** [review]
Looks good.
I do encourage you to use the typedefs they are there for a reason (both ethereum-types Address, and our ContractAddress)

**Comment by fredfortier** [comment]
I was unable to push the merged changes to `develop`.

```
[fredfortier@localhost enigma-core-internal]$ git push
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 1.26 KiB | 643.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/develop.
remote: error: Required status check "continuous-integration/drone/push" is expected.
To github.com:enigmampc/enigma-core.git
 ! [remote rejected] develop -> develop (protected branch hook declined)
error: failed to push some refs to 'git@github.com:enigmampc/enigma-core.git'
```
I'm not sure to understand this error. Please give me some pointers or feel free to merge on your end.

**Pull request merged**
